// SPDX-License-Identifier: MIT
/**
 * Build step: parse LittleLink's brands.css (+ the extracted catalog) into a
 * typed brand manifest (`src/brands.generated.ts`). SPEC §7.
 *
 *   brands.css            → per-brand --button-text / --button-background / --button-border
 *   littlelink-catalog.json → per-brand icon basename + label + alt (from LittleLink index.html)
 *
 * Run: `bun run scripts/build-brands.ts`  (also wired as the package `build`).
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const PKG = join(dirname(fileURLToPath(import.meta.url)), "..");
const css = readFileSync(join(PKG, "brands.css"), "utf8");
const catalog: Record<string, { icon: string; label: string; alt: string }> = JSON.parse(
  readFileSync(join(PKG, "littlelink-catalog.json"), "utf8"),
);
const iconFiles = new Set(readdirSync(join(PKG, "icons")).map((f) => f.replace(/\.svg$/, "")));

type BrandSpec = {
  brand: string;
  label: string;
  text: string;
  background: string;
  border: string;
  icon: string;
  alt: string;
};

function cssVar(body: string, name: string): string {
  const m = body.match(new RegExp(`--button-${name}\\s*:\\s*([^;]+);`, "i"));
  return m?.[1]?.trim() ?? "";
}

function titleCase(key: string): string {
  return key
    .split("-")
    .map((p) => (p ? p[0]!.toUpperCase() + p.slice(1) : p))
    .join(" ");
}

const brands: Record<string, BrandSpec> = {};
// Each CSS rule block: "<selector> { <body> }". Match the brand key from the
// last `.button-<key>` token in the selector (skips the base `.button` rule).
const ruleRe = /([^{}]+)\{([^}]*)\}/g;
const missingIcons: string[] = [];

for (let m = ruleRe.exec(css); m !== null; m = ruleRe.exec(css)) {
  const selector = m[1]!;
  const body = m[2]!;
  const keyMatch = selector.match(/\.button-([a-z0-9-]+)/);
  if (!keyMatch) continue;
  const brand = keyMatch[1]!;
  const background = cssVar(body, "background");
  const text = cssVar(body, "text");
  if (!background && !text) continue; // not a brand color rule
  if (brands[brand]) continue;

  const cat = catalog[brand];
  const icon = cat?.icon && iconFiles.has(cat.icon) ? cat.icon : brand;
  if (!iconFiles.has(icon)) missingIcons.push(brand);

  brands[brand] = {
    brand,
    label: cat?.label ?? titleCase(brand),
    text,
    background,
    border: cssVar(body, "border"),
    icon,
    alt: cat?.alt ?? `${titleCase(brand)} Logo`,
  };
}

const keys = Object.keys(brands).sort();
const ordered: Record<string, BrandSpec> = {};
for (const k of keys) ordered[k] = brands[k]!;

const out = `// SPDX-License-Identifier: MIT
// AUTO-GENERATED by scripts/build-brands.ts — do not edit.
// Source: LittleLink (MIT) brands.css + icons. See NOTICE.
export type BrandSpec = {
  brand: string;
  label: string;
  text: string;
  background: string;
  border: string;
  icon: string;
  alt: string;
};

export const BRANDS: Record<string, BrandSpec> = ${JSON.stringify(ordered, null, 2)};

export const BRAND_KEYS: readonly string[] = ${JSON.stringify(keys)};
`;

writeFileSync(join(PKG, "src", "brands.generated.ts"), out);
console.log(
  `✓ brands.generated.ts — ${keys.length} brands${missingIcons.length ? ` (no icon: ${missingIcons.join(", ")})` : ""}`,
);
