// SPDX-License-Identifier: MIT
// AUTO-GENERATED by scripts/build-brands.ts — do not edit.
// Source: LittleLink (MIT) brands.css + icons. See NOTICE.
export type BrandSpec = {
  brand: string;
  label: string;
  text: string;
  background: string;
  border: string;
  icon: string;
  alt: string;
};

export const BRANDS: Record<string, BrandSpec> = {
  "amazon": {
    "brand": "amazon",
    "label": "Amazon Wishlist",
    "text": "#000000",
    "background": "#FFFFFF",
    "border": "1px solid #212121",
    "icon": "amazon",
    "alt": "Amazon Wishlist Logo"
  },
  "amazon-music": {
    "brand": "amazon-music",
    "label": "Amazon Music",
    "text": "#000000",
    "background": "#25D1DA",
    "border": "",
    "icon": "amazon-music",
    "alt": "Amazon Music Logo"
  },
  "apple-music": {
    "brand": "apple-music",
    "label": "Apple Music",
    "text": "#ffffff",
    "background": "#000000",
    "border": "1px solid #FFFFFF",
    "icon": "apple-music",
    "alt": "Apple Music Logo"
  },
  "apple-music-alt": {
    "brand": "apple-music-alt",
    "label": "Apple Music",
    "text": "#ffffff",
    "background": "",
    "border": "",
    "icon": "apple-music-alt",
    "alt": "Apple Music Logo"
  },
  "apple-podcasts": {
    "brand": "apple-podcasts",
    "label": "Apple Podcasts",
    "text": "#ffffff",
    "background": "#000000",
    "border": "1px solid #FFFFFF",
    "icon": "apple-podcasts",
    "alt": "Apple Podcasts Logo"
  },
  "apple-podcasts-alt": {
    "brand": "apple-podcasts-alt",
    "label": "Apple Podcasts",
    "text": "#ffffff",
    "background": "",
    "border": "",
    "icon": "apple-podcasts-alt",
    "alt": "Apple Podcasts Logo"
  },
  "appstore": {
    "brand": "appstore",
    "label": "Apple",
    "text": "#FFFFFF",
    "background": "#000000",
    "border": "1px solid #FFFFFF",
    "icon": "apple",
    "alt": "Apple Logo"
  },
  "bandcamp": {
    "brand": "bandcamp",
    "label": "Bandcamp",
    "text": "#ffffff",
    "background": "#1d9fc3",
    "border": "",
    "icon": "bandcamp",
    "alt": "Bandcamp Logo"
  },
  "behance": {
    "brand": "behance",
    "label": "Behance",
    "text": "#ffffff",
    "background": "#0057FF",
    "border": "1px solid #FFFFFF",
    "icon": "behance",
    "alt": "Behance Logo"
  },
  "bluesky": {
    "brand": "bluesky",
    "label": "Bluesky",
    "text": "#FFFFFF",
    "background": "#1185FE",
    "border": "",
    "icon": "bluesky",
    "alt": "Bluesky Logo"
  },
  "bluesky-alt": {
    "brand": "bluesky-alt",
    "label": "Bluesky",
    "text": "#000000",
    "background": "#FFFFFF",
    "border": "1px solid #000000",
    "icon": "bluesky-alt",
    "alt": "Bluesky Logo"
  },
  "cal": {
    "brand": "cal",
    "label": "Cal.com",
    "text": "#FFFFFF",
    "background": "#292929",
    "border": "1px solid #FFFFFF",
    "icon": "cal",
    "alt": "Cal.com Logo"
  },
  "calendly": {
    "brand": "calendly",
    "label": "Calendly",
    "text": "#FFFFFF",
    "background": "#006BFF",
    "border": "",
    "icon": "calendly",
    "alt": "Calendly Logo"
  },
  "cash-app": {
    "brand": "cash-app",
    "label": "Cash App",
    "text": "#ffffff",
    "background": "",
    "border": "",
    "icon": "cash-app-dollar",
    "alt": "Cash App Logo"
  },
  "coffee": {
    "brand": "coffee",
    "label": "Buy Me A Coffee",
    "text": "#000000",
    "background": "#ffdd00",
    "border": "",
    "icon": "buy-me-a-coffee",
    "alt": "Buy Me A Coffee Logo"
  },
  "default": {
    "brand": "default",
    "label": "LittleLink",
    "text": "#ffffff",
    "background": "#2457F5",
    "border": "1px solid #ffffff",
    "icon": "littlelink",
    "alt": "LittleLink Logo"
  },
  "dev-to": {
    "brand": "dev-to",
    "label": "Dev.to",
    "text": "#000000",
    "background": "#f5f5f5",
    "border": "1px solid #212121",
    "icon": "dev-to",
    "alt": "Dev.to Logo"
  },
  "discogs": {
    "brand": "discogs",
    "label": "Discogs",
    "text": "#000000",
    "background": "#FFFFFF",
    "border": "1px solid #000000",
    "icon": "discogs",
    "alt": "Discogs Logo"
  },
  "discogs-alt": {
    "brand": "discogs-alt",
    "label": "Discogs",
    "text": "#FFFFFF",
    "background": "#000000",
    "border": "1px solid #FFFFFF",
    "icon": "discogs-alt",
    "alt": "Discogs Logo"
  },
  "discord": {
    "brand": "discord",
    "label": "Discord",
    "text": "#ffffff",
    "background": "#5865F2",
    "border": "",
    "icon": "discord",
    "alt": "Discord Logo"
  },
  "dribbble": {
    "brand": "dribbble",
    "label": "Dribbble",
    "text": "#000000",
    "background": "#FFFFFF",
    "border": "1px solid #212121",
    "icon": "dribbble",
    "alt": "Dribbble Logo"
  },
  "etsy": {
    "brand": "etsy",
    "label": "Etsy",
    "text": "#ffffff",
    "background": "#F45800",
    "border": "",
    "icon": "etsy",
    "alt": "Etsy Logo"
  },
  "faceb": {
    "brand": "faceb",
    "label": "Facebook",
    "text": "#ffffff",
    "background": "#0866FF",
    "border": "",
    "icon": "facebook",
    "alt": "Facebook Logo"
  },
  "figma": {
    "brand": "figma",
    "label": "Figma",
    "text": "#ffffff",
    "background": "#000000",
    "border": "1px solid #FFFFFF",
    "icon": "figma",
    "alt": "Figma Logo"
  },
  "fiverr": {
    "brand": "fiverr",
    "label": "Fiverr",
    "text": "#ffffff",
    "background": "#1DBF73",
    "border": "",
    "icon": "fiverr",
    "alt": "Fiverr Logo"
  },
  "flickr": {
    "brand": "flickr",
    "label": "Flickr",
    "text": "#ffffff",
    "background": "#000000",
    "border": "1px solid #FFFFFF",
    "icon": "flickr",
    "alt": "Flickr Logo"
  },
  "github": {
    "brand": "github",
    "label": "GitHub",
    "text": "#ffffff",
    "background": "#000000",
    "border": "1px solid #FFFFFF",
    "icon": "github",
    "alt": "GitHub Logo"
  },
  "gitlab": {
    "brand": "gitlab",
    "label": "GitLab",
    "text": "#ffffff",
    "background": "#6151b2",
    "border": "",
    "icon": "gitlab",
    "alt": "GitLab Logo"
  },
  "gofundme": {
    "brand": "gofundme",
    "label": "GoFundMe",
    "text": "#ffffff",
    "background": "#02A95C",
    "border": "",
    "icon": "gofundme",
    "alt": "GoFundMe Logo"
  },
  "goodreads": {
    "brand": "goodreads",
    "label": "Goodreads",
    "text": "#333333",
    "background": "#f3f1e6",
    "border": "1px solid #212121",
    "icon": "goodreads",
    "alt": "Goodreads Logo"
  },
  "google-black": {
    "brand": "google-black",
    "label": "Google Drive",
    "text": "#FFFFFF",
    "background": "#000000",
    "border": "1px solid #FFFFFF",
    "icon": "google-drive",
    "alt": "Google Drive Logo"
  },
  "google-scholar": {
    "brand": "google-scholar",
    "label": "Google Scholar",
    "text": "#000000",
    "background": "#FFFFFF",
    "border": "1px solid #212121",
    "icon": "google-scholar",
    "alt": "Google Scholar Logo"
  },
  "hashnode": {
    "brand": "hashnode",
    "label": "Hashnode",
    "text": "#000000",
    "background": "#ffffff",
    "border": "1px solid #212121",
    "icon": "hashnode",
    "alt": "Hashnode Logo"
  },
  "instagram": {
    "brand": "instagram",
    "label": "Instagram",
    "text": "#ffffff",
    "background": "",
    "border": "",
    "icon": "instagram",
    "alt": "Instagram Logo"
  },
  "invites": {
    "brand": "invites",
    "label": "Apple Invites",
    "text": "#FFFFFF",
    "background": "#000000",
    "border": "1px solid #FFFFFF",
    "icon": "apple-invites",
    "alt": "Apple Invites Logo"
  },
  "kick": {
    "brand": "kick",
    "label": "Kick",
    "text": "#ffffff",
    "background": "#000000",
    "border": "1px solid #ffffff",
    "icon": "kick",
    "alt": "Kick Logo"
  },
  "kick-alt": {
    "brand": "kick-alt",
    "label": "Kick",
    "text": "#000000",
    "background": "#01e701",
    "border": "",
    "icon": "kick-alt",
    "alt": "Kick Logo"
  },
  "kickstarter": {
    "brand": "kickstarter",
    "label": "Kickstarter",
    "text": "#ffffff",
    "background": "#05ce78",
    "border": "",
    "icon": "kickstarter",
    "alt": "Kickstarter Logo"
  },
  "kit": {
    "brand": "kit",
    "label": "Kit",
    "text": "#ffffff",
    "background": "#000000",
    "border": "1px solid #FFFFFF",
    "icon": "kit",
    "alt": "Kit Logo"
  },
  "ko-fi": {
    "brand": "ko-fi",
    "label": "Ko-fi",
    "text": "#ffffff",
    "background": "#000000",
    "border": "1px solid #FFFFFF",
    "icon": "ko-fi",
    "alt": "Ko-fi Logo"
  },
  "last-fm": {
    "brand": "last-fm",
    "label": "Last.fm",
    "text": "#ffffff",
    "background": "#D51007",
    "border": "",
    "icon": "last-fm",
    "alt": ""
  },
  "letterboxd": {
    "brand": "letterboxd",
    "label": "Letterboxd",
    "text": "#ffffff",
    "background": "#2c3440",
    "border": "1px solid #FFFFFF",
    "icon": "letterboxd",
    "alt": ""
  },
  "line": {
    "brand": "line",
    "label": "Line",
    "text": "#FFFFFF",
    "background": "#06C755",
    "border": "",
    "icon": "line",
    "alt": "Line Logo"
  },
  "linked": {
    "brand": "linked",
    "label": "LinkedIn",
    "text": "#ffffff",
    "background": "#2867b2",
    "border": "",
    "icon": "linkedin",
    "alt": "LinkedIn Logo"
  },
  "mailchimp": {
    "brand": "mailchimp",
    "label": "Mailchimp",
    "text": "#000000",
    "background": "#FFE01B",
    "border": "",
    "icon": "mailchimp",
    "alt": "Mailchimp Logo"
  },
  "mastodon": {
    "brand": "mastodon",
    "label": "Mastodon",
    "text": "#ffffff",
    "background": "#17063B",
    "border": "1px solid #FFFFFF",
    "icon": "mastodon",
    "alt": "Mastodon Logo"
  },
  "matrix": {
    "brand": "matrix",
    "label": "Matrix",
    "text": "#000000",
    "background": "#ffffff",
    "border": "1px solid #000000",
    "icon": "matrix",
    "alt": "Matrix Logo"
  },
  "medium": {
    "brand": "medium",
    "label": "Medium",
    "text": "#ffffff",
    "background": "#000000",
    "border": "1px solid #FFFFFF",
    "icon": "medium",
    "alt": "Medium Logo"
  },
  "meetup": {
    "brand": "meetup",
    "label": "Meetup",
    "text": "#000000",
    "background": "#ffffff",
    "border": "1px solid #000000",
    "icon": "meetup",
    "alt": "Meetup Logo"
  },
  "meetup-alt": {
    "brand": "meetup-alt",
    "label": "Meetup",
    "text": "#ffffff",
    "background": "#ED1C40",
    "border": "",
    "icon": "meetup-alt",
    "alt": "Meetup Logo"
  },
  "messenger": {
    "brand": "messenger",
    "label": "Messenger",
    "text": "#ffffff",
    "background": "#0866FF",
    "border": "",
    "icon": "messenger",
    "alt": "Messenger Logo"
  },
  "microsoft": {
    "brand": "microsoft",
    "label": "Microsoft",
    "text": "#ffffff",
    "background": "#000000",
    "border": "1px solid #FFFFFF",
    "icon": "microsoft",
    "alt": "Microsoft Logo"
  },
  "notion": {
    "brand": "notion",
    "label": "Notion",
    "text": "#000000",
    "background": "#ffffff",
    "border": "1px solid #212121",
    "icon": "notion",
    "alt": "Notion Logo"
  },
  "obsidian": {
    "brand": "obsidian",
    "label": "Obsidian",
    "text": "#ffffff",
    "background": "#262626",
    "border": "1px solid #ffffff",
    "icon": "obsidian",
    "alt": "Obsidian Logo"
  },
  "onlyfans": {
    "brand": "onlyfans",
    "label": "OnlyFans",
    "text": "#ffffff",
    "background": "#00AEEF",
    "border": "",
    "icon": "onlyfans",
    "alt": "OnlyFans Logo"
  },
  "patreon": {
    "brand": "patreon",
    "label": "Patreon",
    "text": "#ffffff",
    "background": "#000000",
    "border": "1px solid #FFFFFF",
    "icon": "patreon",
    "alt": "Patreon Logo"
  },
  "paypal": {
    "brand": "paypal",
    "label": "PayPal",
    "text": "#ffffff",
    "background": "#002991",
    "border": "1px solid #FFFFFF",
    "icon": "paypal",
    "alt": "PayPal Logo"
  },
  "pinterest": {
    "brand": "pinterest",
    "label": "Pinterest",
    "text": "#000000",
    "background": "#ffffff",
    "border": "1px solid #212121",
    "icon": "pinterest",
    "alt": "Pinterest Logo"
  },
  "playstore": {
    "brand": "playstore",
    "label": "Google Play Store",
    "text": "#FFFFFF",
    "background": "#000000",
    "border": "1px solid #FFFFFF",
    "icon": "google-play",
    "alt": "Google Play Store Logo"
  },
  "product-hunt": {
    "brand": "product-hunt",
    "label": "Product Hunt",
    "text": "#000000",
    "background": "#ffffff",
    "border": "1px solid #212121",
    "icon": "product-hunt",
    "alt": "Product Hunt Logo"
  },
  "reddit": {
    "brand": "reddit",
    "label": "Reddit",
    "text": "#FFFFFF",
    "background": "#FF4500",
    "border": "",
    "icon": "reddit",
    "alt": "Reddit Logo"
  },
  "shop": {
    "brand": "shop",
    "label": "Shop",
    "text": "#ffffff",
    "background": "#5A31F4",
    "border": "",
    "icon": "shop",
    "alt": "Shop Logo"
  },
  "signal": {
    "brand": "signal",
    "label": "Signal",
    "text": "#ffffff",
    "background": "#3B45FD",
    "border": "",
    "icon": "signal",
    "alt": "Signal Logo"
  },
  "signal-alt": {
    "brand": "signal-alt",
    "label": "Signal",
    "text": "#3B45FD",
    "background": "#E3E8FE",
    "border": "1px solid #000000",
    "icon": "signal-alt",
    "alt": "Signal Logo"
  },
  "slack": {
    "brand": "slack",
    "label": "Slack",
    "text": "#000000",
    "background": "#FFFFFF",
    "border": "1px solid #212121",
    "icon": "slack",
    "alt": "Slack Logo"
  },
  "snapchat": {
    "brand": "snapchat",
    "label": "Snapchat",
    "text": "#000000",
    "background": "#fffc00",
    "border": "",
    "icon": "snapchat",
    "alt": "Snapchat Logo"
  },
  "soundcloud": {
    "brand": "soundcloud",
    "label": "SoundCloud",
    "text": "#ffffff",
    "background": "#ff5500",
    "border": "",
    "icon": "soundcloud",
    "alt": "SoundCloud Logo"
  },
  "spotify": {
    "brand": "spotify",
    "label": "Spotify",
    "text": "#191414",
    "background": "#1db954",
    "border": "",
    "icon": "spotify",
    "alt": "Spotify Logo"
  },
  "spotify-alt": {
    "brand": "spotify-alt",
    "label": "Spotify",
    "text": "#FFFFFF",
    "background": "#191414",
    "border": "1px solid #FFFFFF",
    "icon": "spotify-alt",
    "alt": "Spotify Logo"
  },
  "square": {
    "brand": "square",
    "label": "Square",
    "text": "#FFFFFF",
    "background": "#006AFF",
    "border": "",
    "icon": "square",
    "alt": "Square Logo"
  },
  "stack-overflow": {
    "brand": "stack-overflow",
    "label": "Stack Overflow",
    "text": "#000000",
    "background": "#FFFFFF",
    "border": "1px solid #000000",
    "icon": "stack-overflow",
    "alt": "Stack Overflow Logo"
  },
  "steam": {
    "brand": "steam",
    "label": "Steam",
    "text": "#ffffff",
    "background": "",
    "border": "",
    "icon": "steam",
    "alt": "Steam Logo"
  },
  "steam-alt": {
    "brand": "steam-alt",
    "label": "Steam",
    "text": "#ffffff",
    "background": "",
    "border": "1px solid #FFFFFF",
    "icon": "steam",
    "alt": "Steam Logo"
  },
  "strava": {
    "brand": "strava",
    "label": "Strava",
    "text": "#ffffff",
    "background": "#fc5200",
    "border": "",
    "icon": "strava",
    "alt": "Strava Logo"
  },
  "substack": {
    "brand": "substack",
    "label": "Substack",
    "text": "#ffffff",
    "background": "#FF6719",
    "border": "",
    "icon": "substack",
    "alt": "Substack Logo"
  },
  "telegram": {
    "brand": "telegram",
    "label": "Telegram",
    "text": "#ffffff",
    "background": "#3faee8",
    "border": "",
    "icon": "telegram",
    "alt": "Telegram Logo"
  },
  "threads": {
    "brand": "threads",
    "label": "Threads",
    "text": "#FFFFFF",
    "background": "#000000",
    "border": "1px solid #FFFFFF",
    "icon": "threads",
    "alt": "Threads Logo"
  },
  "threema": {
    "brand": "threema",
    "label": "Threema",
    "text": "#000000",
    "background": "#3fe669",
    "border": "",
    "icon": "threema",
    "alt": "Threema Logo"
  },
  "tiktok": {
    "brand": "tiktok",
    "label": "TikTok",
    "text": "#ffffff",
    "background": "#000000",
    "border": "1px solid #FFFFFF",
    "icon": "tiktok",
    "alt": "TikTok Logo"
  },
  "trello": {
    "brand": "trello",
    "label": "Trello",
    "text": "#ffffff",
    "background": "#0065ff",
    "border": "",
    "icon": "trello",
    "alt": "Trello Logo"
  },
  "tumb": {
    "brand": "tumb",
    "label": "Tumblr",
    "text": "#ffffff",
    "background": "#131313",
    "border": "1px solid #FFFFFF",
    "icon": "tumblr",
    "alt": "Tumblr Logo"
  },
  "twitch": {
    "brand": "twitch",
    "label": "Twitch",
    "text": "#ffffff",
    "background": "#9146ff",
    "border": "",
    "icon": "twitch",
    "alt": "Twitch Logo"
  },
  "unsplash": {
    "brand": "unsplash",
    "label": "Unsplash",
    "text": "#000000",
    "background": "#ffffff",
    "border": "1px solid #212121",
    "icon": "unsplash",
    "alt": "Unsplash Logo"
  },
  "venmo": {
    "brand": "venmo",
    "label": "Venmo",
    "text": "#ffffff",
    "background": "#008CFF",
    "border": "",
    "icon": "venmo",
    "alt": "Venmo Logo"
  },
  "vimeo": {
    "brand": "vimeo",
    "label": "Vimeo",
    "text": "#ffffff",
    "background": "#1ab7ea",
    "border": "",
    "icon": "vimeo",
    "alt": "Vimeo Logo"
  },
  "vsco": {
    "brand": "vsco",
    "label": "VSCO",
    "text": "#FFFFFF",
    "background": "#000000",
    "border": "1px solid #FFFFFF",
    "icon": "vsco",
    "alt": "VSCO Logo"
  },
  "whatsapp": {
    "brand": "whatsapp",
    "label": "WhatsApp",
    "text": "#ffffff",
    "background": "#455a64",
    "border": "",
    "icon": "whatsapp",
    "alt": "WhatsApp Logo"
  },
  "wordpress": {
    "brand": "wordpress",
    "label": "WordPress",
    "text": "#ffffff",
    "background": "#3858E9",
    "border": "",
    "icon": "wordpress",
    "alt": "WordPress Logo"
  },
  "x": {
    "brand": "x",
    "label": "X",
    "text": "#FFFFFF",
    "background": "#000000",
    "border": "1px solid #FFFFFF",
    "icon": "x",
    "alt": "X Logo"
  },
  "yt": {
    "brand": "yt",
    "label": "YouTube",
    "text": "#ffffff",
    "background": "#282828",
    "border": "1px solid #FFFFFF",
    "icon": "youtube",
    "alt": "YouTube Logo"
  },
  "yt-alt": {
    "brand": "yt-alt",
    "label": "YouTube",
    "text": "#ffffff",
    "background": "#FF0000",
    "border": "",
    "icon": "youtube-alt",
    "alt": "YouTube Logo"
  },
  "zoom": {
    "brand": "zoom",
    "label": "Zoom",
    "text": "#ffffff",
    "background": "#0B5CFF",
    "border": "1px solid #FFFFFF",
    "icon": "zoom",
    "alt": "Zoom Logo"
  }
};

export const BRAND_KEYS: readonly string[] = ["amazon","amazon-music","apple-music","apple-music-alt","apple-podcasts","apple-podcasts-alt","appstore","bandcamp","behance","bluesky","bluesky-alt","cal","calendly","cash-app","coffee","default","dev-to","discogs","discogs-alt","discord","dribbble","etsy","faceb","figma","fiverr","flickr","github","gitlab","gofundme","goodreads","google-black","google-scholar","hashnode","instagram","invites","kick","kick-alt","kickstarter","kit","ko-fi","last-fm","letterboxd","line","linked","mailchimp","mastodon","matrix","medium","meetup","meetup-alt","messenger","microsoft","notion","obsidian","onlyfans","patreon","paypal","pinterest","playstore","product-hunt","reddit","shop","signal","signal-alt","slack","snapchat","soundcloud","spotify","spotify-alt","square","stack-overflow","steam","steam-alt","strava","substack","telegram","threads","threema","tiktok","trello","tumb","twitch","unsplash","venmo","vimeo","vsco","whatsapp","wordpress","x","yt","yt-alt","zoom"];
